### ISSUE TITLE
NullReferenceException thrown when running get-process in demo

### ISSUE THREAD

**Issue by reznet** [twtseng/PSDrilldownTool#3]
I loaded the demo.json and clicked "chrome" in the get-process results window, and VS debugger stopped at line 260 of PowerShellTask.cs because _pipeline.PipelineStateInfo.Reason.ToString() threw a null reference exception because the Reason property was null.

```
                if (_pipeline.HadErrors)
                {
                    _resultStringBuilder.AppendLine(_pipeline.PipelineStateInfo.Reason.ToString());
                    _taskStatus = Status.FAILED;
                }
```

In the debugger, PipelineStateInfo.State is Running, and Reason is null so it looks like the tool perhaps hasn't waited for powershell to exit yet?

**Comment by twtseng** [comment]
thanks for reporting the issue Jeff! We will work on fixing the issue asap!

**Comment by twtseng** [comment]
Added a check for null before writing the error reasom
